require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SessionLogEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # SessionLogEntry. As you add validations to SessionLogEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "session_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SessionLogEntriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all session_log_entries as @session_log_entries" do
      session_log_entry = SessionLogEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:session_log_entries).should eq([session_log_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested session_log_entry as @session_log_entry" do
      session_log_entry = SessionLogEntry.create! valid_attributes
      get :show, {:id => session_log_entry.to_param}, valid_session
      assigns(:session_log_entry).should eq(session_log_entry)
    end
  end

  describe "GET new" do
    it "assigns a new session_log_entry as @session_log_entry" do
      get :new, {}, valid_session
      assigns(:session_log_entry).should be_a_new(SessionLogEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested session_log_entry as @session_log_entry" do
      session_log_entry = SessionLogEntry.create! valid_attributes
      get :edit, {:id => session_log_entry.to_param}, valid_session
      assigns(:session_log_entry).should eq(session_log_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SessionLogEntry" do
        expect {
          post :create, {:session_log_entry => valid_attributes}, valid_session
        }.to change(SessionLogEntry, :count).by(1)
      end

      it "assigns a newly created session_log_entry as @session_log_entry" do
        post :create, {:session_log_entry => valid_attributes}, valid_session
        assigns(:session_log_entry).should be_a(SessionLogEntry)
        assigns(:session_log_entry).should be_persisted
      end

      it "redirects to the created session_log_entry" do
        post :create, {:session_log_entry => valid_attributes}, valid_session
        response.should redirect_to(SessionLogEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved session_log_entry as @session_log_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        SessionLogEntry.any_instance.stub(:save).and_return(false)
        post :create, {:session_log_entry => { "session_id" => "invalid value" }}, valid_session
        assigns(:session_log_entry).should be_a_new(SessionLogEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SessionLogEntry.any_instance.stub(:save).and_return(false)
        post :create, {:session_log_entry => { "session_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested session_log_entry" do
        session_log_entry = SessionLogEntry.create! valid_attributes
        # Assuming there are no other session_log_entries in the database, this
        # specifies that the SessionLogEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SessionLogEntry.any_instance.should_receive(:update_attributes).with({ "session_id" => "1" })
        put :update, {:id => session_log_entry.to_param, :session_log_entry => { "session_id" => "1" }}, valid_session
      end

      it "assigns the requested session_log_entry as @session_log_entry" do
        session_log_entry = SessionLogEntry.create! valid_attributes
        put :update, {:id => session_log_entry.to_param, :session_log_entry => valid_attributes}, valid_session
        assigns(:session_log_entry).should eq(session_log_entry)
      end

      it "redirects to the session_log_entry" do
        session_log_entry = SessionLogEntry.create! valid_attributes
        put :update, {:id => session_log_entry.to_param, :session_log_entry => valid_attributes}, valid_session
        response.should redirect_to(session_log_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the session_log_entry as @session_log_entry" do
        session_log_entry = SessionLogEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SessionLogEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => session_log_entry.to_param, :session_log_entry => { "session_id" => "invalid value" }}, valid_session
        assigns(:session_log_entry).should eq(session_log_entry)
      end

      it "re-renders the 'edit' template" do
        session_log_entry = SessionLogEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SessionLogEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => session_log_entry.to_param, :session_log_entry => { "session_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested session_log_entry" do
      session_log_entry = SessionLogEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => session_log_entry.to_param}, valid_session
      }.to change(SessionLogEntry, :count).by(-1)
    end

    it "redirects to the session_log_entries list" do
      session_log_entry = SessionLogEntry.create! valid_attributes
      delete :destroy, {:id => session_log_entry.to_param}, valid_session
      response.should redirect_to(session_log_entries_url)
    end
  end

end
